#158434528 Add new ride offer
meshack-mbuvi/ride-my-way pull request #24
Opened 2018-06-23 06:22 UTC by meshack-mbuvi

**What does this PR do?
Adds new ride offer

**Description of Task to be completed?**
- Modify form in new_ride.html to capture necessary details about a ride.
- The form should have:
  - Field to capture start point
  - Field to capture destination
  - Field to capture planned route
  - Field to capture start time 
  - Field to capture available space

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-create-ride-158434528
- Open `new_ride` using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158434528](https://www.pivotaltracker.com/story/show/158434528)

**Screenshots**
![new ride](https://user-images.githubusercontent.com/9263906/41806444-e5adef14-76c6-11e8-995f-f86f42816457.png)

2018-06-23 06:25 UTC, TheSteelGuy commented
Keenly checked and all looks good now

2018-06-23 09:41 UTC, JoshuaOndieki requested changes

2018-06-23 09:41 UTC, JoshuaOndieki commented on ui/new_ride.html
> +						<input type="text" name="destination" id="destination">
I believe the starting point and destination are important details and therefore I suggest setting them as required.

2018-06-25 15:17 UTC, LWanjiru approved these changes
Looks good. It is a good observation that @JoshuaOndieki has made about the field being required, it would be a good thing to remember during implementation, however, for now, we are not implementing core functionality. Can be merged.

2018-06-25 15:37 UTC, merged